var bicycleRental = {
  loops: null,
  konflik: 223,
  dampak: 443103,
  luas: 1432773.18,
  investasi: "Rp 10,23 T",
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [113.79106521606, -8.4216362794148],
      },
      properties: {
        idx: "54",
        nomor_kejadian: "3509060002",
        tgl_kejadian: "2013-03-04",
        tahun: "2013",
        judul:
          "Sengketa lahan Masyarakat Curahnongko dan Andongrejo Dengan PTPN XII",
        clip: "",
        narasi: "",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "PTPN",
        status_konflik: "PS",
        status_konflik_proses: "Mediasi",
        tgl_proses: "2013-04-04",
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "332",
        investasi: "0",
        dampak: "1500",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "35",
        kd_kabupaten: "3509",
        kd_kecamatan: "",
        kd_desa: "",
        longitude: "113.79106521606",
        latitude: "-8.4216362794148",
        sumber: "KPA",
        created: "2017-04-04 12:18:49",
        creator: "adminp",
        edited: "2023-06-20 14:19:46",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Jawa Timur",
        nm_kabupaten: "Kab. Jember",
        tipe: null,
        id_enc: "YlBjalpBbng1NzQ",
        short_narasi: "<b>Narasi:</b><br>",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [113, -8] },
      properties: {
        idx: "55",
        nomor_kejadian: "3509110001",
        tgl_kejadian: "2013-04-04",
        tahun: "2013",
        judul: "Sengketa lahan mangaran",
        clip: "",
        narasi:
          "Kasus lama yang belum tuntas menduduki lahan sejak 2000, satu ditahan karena memasuki lahan PTPN tanpa izin, 1 lagi DPO",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "PTPN",
        status_konflik: "PS",
        status_konflik_proses: "Mediasi",
        tgl_proses: "2013-05-04",
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "1027",
        investasi: "0",
        dampak: "690",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "35",
        kd_kabupaten: "3509",
        kd_kecamatan: "",
        kd_desa: "",
        longitude: "113",
        latitude: "-8",
        sumber: "KPA",
        created: "2017-04-04 13:22:09",
        creator: "adminp",
        edited: "2023-01-09 11:52:36",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Jawa Timur",
        nm_kabupaten: "Kab. Jember",
        tipe: null,
        id_enc: "TTl0M29udllkQnM",
        short_narasi:
          "<b>Narasi:</b><br>Kasus lama yang belum tuntas menduduki lahan sejak 2000, satu ditahan karena memasuki lahan PTPN tanpa izin, 1 lagi DPO",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [111.09066009521, -7.516750886972],
      },
      properties: {
        idx: "56",
        nomor_kejadian: "IM_30",
        tgl_kejadian: "2013-04-04",
        tahun: "2013",
        judul: "Konflik Agraria Warga Desa Sambirejo dengan   PTPN  IX ",
        clip: "Konflik yang melibatkan warga Sambirejo Kabupten Sragen Jawa Tengah dengan PTPN IX diawali dengan upaya perluasan areal lahan perkebunan PTPN IX. Konflik ada di delapan titik Sambi yaitu Desa Sukorejo, Jambeyan, Sambi,Dawung, Sambirejo, Kadipiro, Musuk dan Jetis. Sengketa lahan seluas 425ha ini sudah terjadi sejak 1965. Hak atas tanah yang dimiliki oleh masyarakat berdasarkan  Surat Keputusan yang dikeluarkan oleh Kepala Inspeksi Agraria Daerah Jawa Tengah (KINAD) No.2971X1172/DC/64 dan 3891z/173/72/DC164 pada 4 Januari 1964. Saat itu juga PTPN IX berkeinginan untuk memperluas areal perkebunannya dengan cara menyewa pada masyarakat, namun upaya perluasan itu mendapatkan penolakan dari masyarakat. Satu tahun kemudian pada tahun 1965 setelah peristiwa GESTOK (Gerakan Satu Oktober) terjadi pengusiran terhadap masyarakat petani penggarap lahan beserta tempat tinggal serta penangkapan dengan munculnya isu PKI, selanjutnya PTPN IX secara sepihak (tanpa persetujuan masyrakat) mengambil alih hak atas tanah tersebut.  ",
        narasi:
          "Konflik yang melibatkan warga Sambirejo Kabupten Sragen Jawa Tengah dengan PTPN IX diawali dengan upaya perluasan areal lahan perkebunan PTPN IX. Konflik ada di delapan titik Sambi yaitu Desa Sukorejo, Jambeyan, Sambi,Dawung, Sambirejo, Kadipiro, Musuk dan Jetis. Sengketa lahan seluas 425ha ini sudah terjadi sejak 1965. Hak atas tanah yang dimiliki oleh masyarakat berdasarkan  Surat Keputusan yang dikeluarkan oleh Kepala Inspeksi Agraria Daerah Jawa Tengah (KINAD) No.2971X1172/DC/64 dan 3891z/173/72/DC164 pada 4 Januari 1964. Saat itu juga PTPN IX berkeinginan untuk memperluas areal perkebunannya dengan cara menyewa pada masyarakat, namun upaya perluasan itu mendapatkan penolakan dari masyarakat. Satu tahun kemudian pada tahun 1965 setelah peristiwa GESTOK (Gerakan Satu Oktober) terjadi pengusiran terhadap masyarakat petani penggarap lahan beserta tempat tinggal serta penangkapan dengan munculnya isu PKI, selanjutnya PTPN IX secara sepihak (tanpa persetujuan masyrakat) mengambil alih hak atas tanah tersebut.  \n  \nSaat memasuki era reformasi pada tahun 1998, Masyarakat mulai melakukan perjuangan untuk mendapatkan kembali hak atas tanahnya. Perjuangan dilakukan oleh warga delapan desa antara lain: Desa Sukorejo; Jambeyan; Sambi, Dawung; Sambirejo; Kadipiro; Musuk dan Jetis. Setelah mengetahui HGU PTPN IX akan habis masa berlakunya pada 31 Desember 2006, perjuangan yang dilakukan semakin massif dan mulai timbul keyakinan di masyarakat petani penggarap keyakinan akan mendapatkan hak atas tanahnya kembali. \nBerbagai cara diupayakan oleh petani untuk mendapatkan haknya kembali, diantaanya adalah mendatangi DPR RI, Komnas HAM, Ombudsman, Kementerian Keuangan, Kementrian BUMN, Kementerian Pertanian dan Kementerian Dalam Negeri. Perjuangan ini mulai mendapat titik terang pada saat DPR RI membentuk Pansus Pertanahan, 15 Januari 2005. Walau pansus ini bertujuanuntuk menyelesaikan masalah kasus tanah yang ada di Sambirejo, ternyata keberadaan pansus tidak juga dapat mengembalikan hak atas tanah petani. \nSetelah berhasil menguasi secara fisik tanah HGU PTPN IX yang masa berlakunya HGU PTPN IX habis, petani yang berjuang untuk mendapatkan hak atas tanahnya kembali yang tergabung dalam, Forum Peduli Kebenaran dan Keadilan Sambirejo (FPKKS),.mendesak BPN RI segera merelisaikan tuntutan warga untuk mengembalikan hak atas tanah mereka yang telah diambil alih oleh PTPN IX.\nPada 4 September2014 dilakukan pemetaan wilayah konflik antara warga, Kanwil BPN Jawa Tengah dan Kantor Pertanahan Kabupaten Sragen, Pemda Sragen, Dinas Perkebunan (provinsi dan kota), Dinas Kehutanan (provinsi dan kota), Konsorsium Pembaruan Agraria (KPA) dan Lembaga Studi dan Advokasi Masyarakat (ELSAM).\nPerjuangan yang dilakukan oleh petani penggarap yang tergabung dalam FPKKS berujung pada tindak kekerasan yang dilakukan oleh pihak perkebunan dan aparat keamanan. Pasca setelah dilakukanya pemetaan provokasi dilakukan oleh pihak perkebunan dan kepolisian, salah satunya dengan menyerang petani dengan menurunkan 5000 buruh perkebunan. Tindakan penyerangan ini akhirnya dibalas oleh petani dengan merusak tanaman perkebunan. Dan tindakan yang dilakukan petani berakhir pada tindak kriminalisasi kepada tiga petani yaitu Sunarji, Sarjimin, dan Suparno dengan vonis hukuman 1,5 tahun karena dituduh dengan pasal 170 KUHP serta pasal 351 dan 406 jo pasal 55, namun proses penangkapannya tidak diawali dengan proses penyelidikan kepolisian",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "PTPN",
        status_konflik: "PS",
        status_konflik_proses: "Mediasi",
        tgl_proses: "2013-09-04",
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "446",
        investasi: "0",
        dampak: "2451",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "33",
        kd_kabupaten: "3314",
        kd_kecamatan: "331405",
        kd_desa: "",
        longitude: "111.09066009521",
        latitude: "-7.516750886972",
        sumber: "KPA",
        created: "2017-04-04 14:34:53",
        creator: "adminp",
        edited: "2020-12-16 17:02:44",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Jawa Tengah",
        nm_kabupaten: "Kab. Sragen",
        tipe: null,
        id_enc: "cHAta2JMMVdwVkk",
        short_narasi:
          "<b>Gambaran Singkat:</b><br>Konflik yang melibatkan warga Sambirejo Kabupten Sragen Jawa Tengah dengan PTPN IX diawali dengan upaya perluasan areal lahan perkebunan PTPN IX. Konflik ada di delapan titik Sambi yaitu Desa Sukorejo, Jambeyan, Sambi,Dawu...",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [109.58724975586, -7.3378996779321],
      },
      properties: {
        idx: "57",
        nomor_kejadian: "3304120007",
        tgl_kejadian: "2017-04-04",
        tahun: "2017",
        judul:
          "Sengketa Lahan Tanah Telantar eks Perkebunan Petani Banjarnegara",
        clip: "",
        narasi:
          "sejarah tanah ini adalah eks perkebunan Belanda, Indonesia merdeka diambil alih oleh Negara dan pada tahun 1960-an diberikan HGU kepada PT. Pakisadji Banjumas seluas 76,61 ha yang diperuntukan untuk perkebunan kopi. Pada masa izin HGU pertama operasional PT. Pakisadja Banjumas berjalan dengan lancar namun memasuki HGU yang kedua barulah ditelantarkan yakni tahun 1986 hingga masyarakat melakukan penanaman.\n\nDi lahan tersebut dan hingga saat ini tetap menguasai lahan seluas 76,61 ha dengan bermacam \u2013 macam komoditas pertanian, sebenarnya pada tahun 2010 PT. Pakisadji Banjumas mengajukan perpanjangan HGU ke Pemerintah Daerah namun ditolak oleh Bupati Banjar Negara alasannya PT. Pakisadji Banjumas telah menelantarkan lahan serta menyalahgunakan untuk peruntukan lahannya. pada tahun 2010 juga dengan ditolaknya perpanjangan HGU PT. Pakisadji Banjumas, Pemerintah Daerah mengajukan permohonan pengembalian asset PT. Pakisadji Banjumas kepada Pemda ke BPN RI karena Pemda akan membangun agrowisata dilahan tersebut sedangkan lahan sudah sepenuhnya dikuasai masyarakat yang tergabung dalam Himpunan Tani Masyarakat Banjar Negara sejak tahun 1986 hingga sekarang.",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "Eks-Perkebunan",
        status_konflik: "PS",
        status_konflik_proses: "Mediasi",
        tgl_proses: "2017-04-04",
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "77",
        investasi: "0",
        dampak: "555",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "33",
        kd_kabupaten: "3307",
        kd_kecamatan: "",
        kd_desa: "",
        longitude: "109.58724975586",
        latitude: "-7.3378996779321",
        sumber: "KPA",
        created: "2017-04-04 15:11:41",
        creator: "adminp",
        edited: "2020-12-16 17:01:57",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Jawa Tengah",
        nm_kabupaten: "Kab. Wonosobo",
        tipe: null,
        id_enc: "d3l0bWlDaWswa2s",
        short_narasi:
          "<b>Narasi:</b><br>sejarah tanah ini adalah eks perkebunan Belanda, Indonesia merdeka diambil alih oleh Negara dan pada tahun 1960-an diberikan HGU kepada PT. Pakisadji Banjumas seluas 76,61 ha yang diperuntukan untuk perkebunan kopi. Pada masa izin H...",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [110.96238613129, -6.9926770283748],
      },
      properties: {
        idx: "58",
        nomor_kejadian: "3315120011",
        tgl_kejadian: "2013-01-04",
        tahun: "2013",
        judul: "Sengketa Lahan Desa Sedayu",
        clip: "",
        narasi: "",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "Perum Perhutani",
        status_konflik: "PS",
        status_konflik_proses: "Mediasi",
        tgl_proses: "2013-02-04",
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "225",
        investasi: "0",
        dampak: "975",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "33",
        kd_kabupaten: "3302",
        kd_kecamatan: "",
        kd_desa: "",
        longitude: "110.96238613129",
        latitude: "-6.9926770283748",
        sumber: "KPA",
        created: "2017-04-04 15:33:40",
        creator: "adminp",
        edited: "2020-12-16 17:03:46",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Jawa Tengah",
        nm_kabupaten: "Kab. Banyumas",
        tipe: null,
        id_enc: "d0U0QmRYeHk4ejQ",
        short_narasi: "<b>Narasi:</b><br>",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [122.9770731926, -0.63273097447073],
      },
      properties: {
        idx: "66",
        nomor_kejadian: "50",
        tgl_kejadian: "2017-04-05",
        tahun: "2017",
        judul:
          "Konflik Masyarakat Desa Toiba dengan PT Wiramas Permai dan PT.SM Patipati",
        clip: "Orang Toiba sejak zaman kerajaan Banggai [sekitar tahun 1800] telah memanfaatkan Patipati sebgai areal penggembalaan ternak. Untuk lokasi berkebun berada di sebalah bara Patipati.  Tahun 1999, Pemerin",
        narasi:
          "Pusar Banggai juga melaporkan perusahaan sawit di Banggai telah merusak kawasan konservasi. Dari tiga perusahaan sawit, dua menyerobot wilayah hutan konservasi, yakni PT Kurnia Luwuk Sejati, di kawasan Suaka Margasatwa Bakiriang. Lalu, PT Wira Mas Permai menyerobot Cagar Alam Pati-pati. Warga Kecamatan Bualemo mengirim surat penolakan ke DPRD Kabupaten Banggai, agar izin hak guna usaha (HGU) PT Wira Mas Permai, tidak diterbitkan. Namun rekomendasi DPRD Kabupaten Banggai nomor : 005/117 DPRD tertanggal 29 Juli 2009 tidak dijadikan pegangan perusahaan. tetap menggusur. Warga sudah mengajukan penolakan kepada perusahaan yang memasuki kawasan konservasi. Warga khawatir, jika kawasan hutan dan Cagar Alam Pati-pati dibuka, akan menerima dampak buruk. Karena sumber air yang dialirkan dari daerah aliran sungai (DAS) Mayayap, akan kering dan sebagian satwa di kawasan itu akan menjadi hama bagi pertanian warga yang bersandar pada hutan di Kecamatan Bualemo. akibat ekspansi perkebunan sawit memaksa masyarakat pindah beralih olah tanam menjadi buruh di tanah sendiri, membuka ruang konflik sesama warga dan tokoh adat.",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "Perkebunan Kelapa Sawit",
        status_konflik: "BD",
        status_konflik_proses: null,
        tgl_proses: null,
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "5972",
        investasi: "0",
        dampak: "254",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "72",
        kd_kabupaten: "7201",
        kd_kecamatan: "",
        kd_desa: "",
        longitude: "122.9770731926",
        latitude: "-0.63273097447073",
        sumber: "SLPP Sulawasi Tengah, YMP",
        created: "2017-04-05 17:37:20",
        creator: "adminp",
        edited: "2023-01-09 13:33:13",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Sulawesi Tengah",
        nm_kabupaten: "Kab. Banggai",
        tipe: null,
        id_enc: "UVdSTTBOS3U5d2s",
        short_narasi:
          "<b>Gambaran Singkat:</b><br>Orang Toiba sejak zaman kerajaan Banggai [sekitar tahun 1800] telah memanfaatkan Patipati sebgai areal penggembalaan ternak. Untuk lokasi berkebun berada di sebalah bara Patipati.  Tahun 1999, Pemerin",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [120.03275871277, -0.62723814245977],
      },
      properties: {
        idx: "72",
        nomor_kejadian: "51",
        tgl_kejadian: "2017-05-04",
        tahun: "2017",
        judul: "Masyarakat Desa Uevolo dengan perkebunan kelapa sawit ",
        clip: "Desa Uevolo merupakan pemekaran dari Desa Marantale. Pad tahun 2016,  masyarakat Uevolo dan desa lainnya di Kecamatan Ampibabo dan Siniu tengah diresahkan oleh masuknya investasi perkebunan besar kelapa sawit di wilayah tersebut. Tercatat 2 perusahaan besar yakni PT. Ampibabo dan PT. Agri Toribulu. ",
        narasi:
          "Desa Uevolo merupakan pemekaran dari Desa Marantale. Pad tahun 2016,  masyarakat Uevolo dan desa lainnya di Kecamatan Ampibabo dan Siniu tengah diresahkan oleh masuknya investasi perkebunan besar kelapa sawit di wilayah tersebut. Tercatat 2 perusahaan besar yakni PT. Ampibabo dan PT. Agri Toribulu. 2 perusahaan ini telah mengantongi izin lokasi dari Bupati Parigi Moutong yang meliputi areal di 2 kecamatan tersebut. Sebagian besar calon lokasi HGU 2 perusahaan ini adalah areal perkebunan milik warga",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "Perkebunan Kelapa Sawit",
        status_konflik: "BD",
        status_konflik_proses: null,
        tgl_proses: null,
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "998.2",
        investasi: "0",
        dampak: "213",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "72",
        kd_kabupaten: "7208",
        kd_kecamatan: "",
        kd_desa: "",
        longitude: "120.03275871277",
        latitude: "-0.62723814245977",
        sumber: "SLPP Sulawesi Tengah / Y MP & KPA Likunggavali",
        created: "2017-05-04 18:17:14",
        creator: "adminp",
        edited: "2023-01-09 14:07:54",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Sulawesi Tengah",
        nm_kabupaten: "Kab. Parigi Moutong",
        tipe: null,
        id_enc: "VmZsclFRcmZFc00",
        short_narasi:
          "<b>Gambaran Singkat:</b><br>Desa Uevolo merupakan pemekaran dari Desa Marantale. Pad tahun 2016,  masyarakat Uevolo dan desa lainnya di Kecamatan Ampibabo dan Siniu tengah diresahkan oleh masuknya investasi perkebunan besar kelapa sawit di wilayah te...",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [119.5915944, -0.863911111] },
      properties: {
        idx: "77",
        nomor_kejadian: "55",
        tgl_kejadian: "2017-05-04",
        tahun: "2017",
        judul:
          "Pemukiman dan areal berkebun masyarakat masuk dalam eks lahan HGU UD Maju",
        clip: "Pemukiman dan areal berkebun masyarakat masuk dalam eks lahan HGU UD Maju sejak tahun 1980.  Lokasi ini juga merupakan Eks lahan HGU UD Maju Tahun 1989",
        narasi:
          "Pemukiman dan areal berkebun masyarakat masuk dalam lokasi eks lahan HGU UD Maju ejak tahun 1980.  Lokasi ini juga merupakan Eks lahan HGU UD Maju Tahun 1989",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "Eks-Perkebunan",
        status_konflik: "BD",
        status_konflik_proses: null,
        tgl_proses: null,
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "274",
        investasi: "0",
        dampak: "120",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "72",
        kd_kabupaten: "7203",
        kd_kecamatan: "",
        kd_desa: "",
        longitude: "119.5915944",
        latitude: "-0.863911111",
        sumber: "SLPP Sulawesi Tengah / YPR",
        created: "2017-05-04 19:24:31",
        creator: "adminp",
        edited: "2023-01-09 13:32:12",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Sulawesi Tengah",
        nm_kabupaten: "Kab. Donggala",
        tipe: null,
        id_enc: "dlN1Q2o2RkJmMFE",
        short_narasi:
          "<b>Gambaran Singkat:</b><br>Pemukiman dan areal berkebun masyarakat masuk dalam eks lahan HGU UD Maju sejak tahun 1980.  Lokasi ini juga merupakan Eks lahan HGU UD Maju Tahun 1989",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [112.44912385941, -2.3765708013198],
      },
      properties: {
        idx: "80",
        nomor_kejadian: "001",
        tgl_kejadian: "2004-04-08",
        tahun: "2004",
        judul: "Konflik Desa Biru Maju dengan PT. Buana Arta Sejahtera",
        clip: "",
        narasi: "",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "Perkebunan Kelapa Sawit",
        status_konflik: "PS",
        status_konflik_proses: "Mediasi",
        tgl_proses: "2017-05-08",
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "657.77",
        investasi: "0",
        dampak: "700",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "62",
        kd_kabupaten: "6202",
        kd_kecamatan: "",
        kd_desa: "",
        longitude: "112.44912385941",
        latitude: "-2.3765708013198",
        sumber:
          "DinasPerkebunan Provinsi_Gangguan Usaha Perkebunan 2013, Laporan Masuk WALHI Kalteng 2011",
        created: "2017-05-08 20:29:54",
        creator: "adminkalteng",
        edited: "2023-01-09 13:26:53",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Kalimantan Tengah",
        nm_kabupaten: "Kab. Kotawaringin Timur",
        tipe: null,
        id_enc: "SUczMV9TaWdZRGM",
        short_narasi: "<b>Narasi:</b><br>",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [113.92806631142, -1.8301568777121],
      },
      properties: {
        idx: "105",
        nomor_kejadian: "67",
        tgl_kejadian: "2016-05-09",
        tahun: "2016",
        judul: "Penyerobotan Lahan Masyarakat Desa Ramang oleh Perusahaan ",
        clip: "PT. AGL Menggusur kebun dan ladang masyarakat seluas sekitar 800 Ha. Perusahaan tidak pernah melakukan sosialisasi, apalagi membeli tanah ke warga. Warga menolak PT.AGL, menuntut ganti rugi tanam tumbuh, dan menuntut pengembalian tanah.\n",
        narasi:
          "PT. AGL Menggusur kebun dan ladang masyarakat seluas sekitar 800 Ha. Perusahaan tidak pernah melakukan sosialisasi, apalagi membeli tanah ke warga. Warga menolak PT.AGL, menuntut ganti rugi tanam tumbuh, dan menuntut pengembalian tanah.",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "Perkebunan Kelapa Sawit",
        status_konflik: "BD",
        status_konflik_proses: null,
        tgl_proses: null,
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "800",
        investasi: "0",
        dampak: "0",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "62",
        kd_kabupaten: "6211",
        kd_kecamatan: "",
        kd_desa: "",
        longitude: "113.9280663114199",
        latitude: "-1.830156877712149",
        sumber: "SLPP Kalteng / Walhi Kalteng",
        created: "2017-05-09 08:24:38",
        creator: "adminp",
        edited: "2023-01-09 11:59:25",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Kalimantan Tengah",
        nm_kabupaten: "Kab. Pulang Pisau",
        tipe: null,
        id_enc: "bUxxN3Z3MFdpQjQ",
        short_narasi:
          "<b>Gambaran Singkat:</b><br>PT. AGL Menggusur kebun dan ladang masyarakat seluas sekitar 800 Ha. Perusahaan tidak pernah melakukan sosialisasi, apalagi membeli tanah ke warga. Warga menolak PT.AGL, menuntut ganti rugi tanam tumbuh, dan menuntut penge...",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [114.464112, -2.500733] },
      properties: {
        idx: "109",
        nomor_kejadian: "68",
        tgl_kejadian: "2014-05-09",
        tahun: "2014",
        judul: "PT. Kalimantan Citra Lestari VS Warga Mantangai Hulu",
        clip: "Penolakan terhadap perusahaan perkebunan sawit karena berada dalam wilayah kelola warga. Penyerobotan lahan kelola warga dan kelompok 3 tani.",
        narasi: "",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "Perkebunan Kelapa Sawit",
        status_konflik: "BD",
        status_konflik_proses: null,
        tgl_proses: null,
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "0",
        investasi: "0",
        dampak: "0",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "62",
        kd_kabupaten: "6203",
        kd_kecamatan: "",
        kd_desa: "",
        longitude: "114.464112",
        latitude: "-2.500733",
        sumber: "SLPP Kalteng / Walhi Kalteng",
        created: "2017-05-09 08:31:44",
        creator: "adminp",
        edited: "2023-01-09 12:34:29",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Kalimantan Tengah",
        nm_kabupaten: "Kab. Kapuas",
        tipe: null,
        id_enc: "V18tQXVnVnpLS3c",
        short_narasi:
          "<b>Gambaran Singkat:</b><br>Penolakan terhadap perusahaan perkebunan sawit karena berada dalam wilayah kelola warga. Penyerobotan lahan kelola warga dan kelompok 3 tani.",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [114.37711715698, -2.1977564527528],
      },
      properties: {
        idx: "125",
        nomor_kejadian: "003",
        tgl_kejadian: "2010-07-01",
        tahun: "2010",
        judul:
          "Konflik Masyarakat Sei Ahas dengan PT. Rezeki Alam Semesta Raya",
        clip: "",
        narasi: "",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "Perkebunan Kelapa Sawit",
        status_konflik: "PS",
        status_konflik_proses: "",
        tgl_proses: "2017-05-09",
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "0",
        investasi: "0",
        dampak: "0",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "62",
        kd_kabupaten: "6203",
        kd_kecamatan: "",
        kd_desa: "",
        longitude: "114.37711715698",
        latitude: "-2.1977564527528",
        sumber: "WALHI KALTENG",
        created: "2017-05-09 09:47:40",
        creator: "adminkalteng",
        edited: "2023-01-09 12:46:23",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Kalimantan Tengah",
        nm_kabupaten: "Kab. Kapuas",
        tipe: null,
        id_enc: "WFdnamNqTWxFU2M",
        short_narasi: "<b>Narasi:</b><br>",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [111.4080619812, -2.3922642178429],
      },
      properties: {
        idx: "132",
        nomor_kejadian: "001",
        tgl_kejadian: "2008-06-01",
        tahun: "2008",
        judul:
          "Konflik Plasma Masyarakat Desa Sukajaya dengan PT. Bumitama Gunajaya Abadi",
        clip: "",
        narasi: "",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "Perkebunan Kelapa Sawit",
        status_konflik: "PS",
        status_konflik_proses: "Hukum",
        tgl_proses: "2017-05-09",
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "111",
        investasi: "0",
        dampak: "423",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "62",
        kd_kabupaten: "6201",
        kd_kecamatan: "",
        kd_desa: "",
        longitude: "111.4080619812",
        latitude: "-2.3922642178429",
        sumber: "WALHI KALTENG",
        created: "2017-05-09 09:55:12",
        creator: "adminkalteng",
        edited: "2023-01-09 12:59:59",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Kalimantan Tengah",
        nm_kabupaten: "Kab. Kotawaringin Barat",
        tipe: null,
        id_enc: "ZG9mOFhNVm1zYXc",
        short_narasi: "<b>Narasi:</b><br>",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [111.46814346313, -2.3384084726746],
      },
      properties: {
        idx: "135",
        nomor_kejadian: "002",
        tgl_kejadian: "2008-06-01",
        tahun: "2008",
        judul:
          "Konflik Plasma Masyarakat Desa Riam Durian dengan PT. Bumitama Gunajaya Abadi",
        clip: "",
        narasi: "",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "Perkebunan Kelapa Sawit",
        status_konflik: "PS",
        status_konflik_proses: "Hukum",
        tgl_proses: "2017-05-09",
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "0",
        investasi: "0",
        dampak: "305",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "62",
        kd_kabupaten: "6201",
        kd_kecamatan: "",
        kd_desa: "",
        longitude: "111.46814346313",
        latitude: "-2.3384084726746",
        sumber: "WALHI KALTENG",
        created: "2017-05-09 09:58:37",
        creator: "adminkalteng",
        edited: "2023-01-09 12:59:58",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Kalimantan Tengah",
        nm_kabupaten: "Kab. Kotawaringin Barat",
        tipe: null,
        id_enc: "S0Nxbl9rSXY5aFE",
        short_narasi: "<b>Narasi:</b><br>",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [111.46883010864, -2.405985090655],
      },
      properties: {
        idx: "138",
        nomor_kejadian: "003",
        tgl_kejadian: "2008-06-01",
        tahun: "2008",
        judul:
          "konflik Plasma Masyarakat Desa kinjil dengan Pt. Bumitama Gunajaya Abadi",
        clip: "",
        narasi: "",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "Perkebunan Kelapa Sawit",
        status_konflik: "PS",
        status_konflik_proses: "Hukum",
        tgl_proses: "2017-05-09",
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "0",
        investasi: "0",
        dampak: "215",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "62",
        kd_kabupaten: "6201",
        kd_kecamatan: "",
        kd_desa: "",
        longitude: "111.46883010864",
        latitude: "-2.405985090655",
        sumber: "WALHI KALTENG",
        created: "2017-05-09 10:01:56",
        creator: "adminkalteng",
        edited: "2023-01-09 12:59:52",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Kalimantan Tengah",
        nm_kabupaten: "Kab. Kotawaringin Barat",
        tipe: null,
        id_enc: "d2hoV1BtamtpcXM",
        short_narasi: "<b>Narasi:</b><br>",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [122.21646308899, -1.4493540716333],
      },
      properties: {
        idx: "143",
        nomor_kejadian: "106",
        tgl_kejadian: "2017-05-09",
        tahun: "2017",
        judul: "Lahan Masyarakat Desa Piondo diserobot PT BHP",
        clip: "",
        narasi:
          "Desa Transmigrasi tahun 1980-an. Masalah agraria yang terjadi adalah konflik antara masyarakat dengan PT Berkat Hutan Pusaka (BHP) sebagai pihak yang melaksanakan program Hutan Tanaman Industri (HTI) dengan alas hukum Keputusan Mentri Kehutanan Nomor: 146/kpts-II/1996 tanggal 4 April 1996 seluas 13.400 Hektar.  PT BHP melanggar hukum karena melaksanakan program itu menyerobot tanah masyarakat yang bersetifikat, dan kemudian sama sekali tidak beroperasi sejak tahun 2000, lantas pada tahun 2006 mengalih fungsi kawasan tersebut menjadi perkebunan kelapa sawit tanpa izin\n\n",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "Perkebunan Kelapa Sawit",
        status_konflik: "BD",
        status_konflik_proses: null,
        tgl_proses: null,
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "786",
        investasi: "0",
        dampak: "0",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "72",
        kd_kabupaten: "7201",
        kd_kecamatan: "",
        kd_desa: "",
        longitude: "122.21646308899",
        latitude: "-1.4493540716333",
        sumber: "SLPP Sulawesi Tengah / YMP",
        created: "2017-05-09 10:14:35",
        creator: "adminsulteng",
        edited: "2023-01-09 13:32:00",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Sulawesi Tengah",
        nm_kabupaten: "Kab. Banggai",
        tipe: null,
        id_enc: "MmRqbWpQejliSE0",
        short_narasi:
          "<b>Narasi:</b><br>Desa Transmigrasi tahun 1980-an. Masalah agraria yang terjadi adalah konflik antara masyarakat dengan PT Berkat Hutan Pusaka (BHP) sebagai pihak yang melaksanakan program Hutan Tanaman Industri (HTI) dengan alas hukum Keputusan Ment...",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [111.38299942017, -2.3819734731057],
      },
      properties: {
        idx: "145",
        nomor_kejadian: "004",
        tgl_kejadian: "2008-06-01",
        tahun: "2008",
        judul:
          "Konflik Plasma Masyarakat Desa Dawak dengan PT. Bumitama Gunajaya Abadi",
        clip: "",
        narasi: "",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "Perkebunan Kelapa Sawit",
        status_konflik: "PS",
        status_konflik_proses: "Hukum",
        tgl_proses: "2017-05-09",
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "0",
        investasi: "0",
        dampak: "525",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "62",
        kd_kabupaten: "6201",
        kd_kecamatan: "",
        kd_desa: "",
        longitude: "111.38299942017",
        latitude: "-2.3819734731057",
        sumber: "WALHI KALTENG",
        created: "2017-05-09 10:16:47",
        creator: "adminkalteng",
        edited: "2023-01-09 12:59:51",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Kalimantan Tengah",
        nm_kabupaten: "Kab. Kotawaringin Barat",
        tipe: null,
        id_enc: "MzBNbWVaVzZEQ3c",
        short_narasi: "<b>Narasi:</b><br>",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [122.24985122681, -1.414002867624],
      },
      properties: {
        idx: "149",
        nomor_kejadian: "107",
        tgl_kejadian: "2017-05-09",
        tahun: "2017",
        judul: "PT BHP menyerobot tanah masyarakat Bukit Jaya",
        clip: "",
        narasi:
          "Desa Transmigrasi tahun 1980-an. Masalah agraria yang terjadi adalah konflik antara masyarakat dengan PT Berkat Hutan Pusaka (BHP) sebagai pihak yang melaksanakan program Hutan Tanaman Industri (HTI) dengan alas hukum Keputusan Mentri Kehutanan Nomor: 146/kpts-II/1996 tanggal 4 April 1996 seluas 13.400 Hektar.  PT BHP melanggar hukum karena melaksanakan program itu menyerobot tanah masyarakat yang bersetifikat, dan kemudian sama sekali tidak beroperasi sejak tahun 2000, lantas pada tahun 2006 mengalih fungsi kawasan tersebut menjadi perkebunan kelapa sawit tanpa izin.",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "Perkebunan Kelapa Sawit",
        status_konflik: "BD",
        status_konflik_proses: null,
        tgl_proses: null,
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "163",
        investasi: "0",
        dampak: "0",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "72",
        kd_kabupaten: "7201",
        kd_kecamatan: "",
        kd_desa: "",
        longitude: "122.24985122681",
        latitude: "-1.414002867624",
        sumber: "SLPP Sulawesi Tengah / KPA & FRAS Sulteng",
        created: "2017-05-09 10:35:55",
        creator: "adminsulteng",
        edited: "2023-01-09 13:31:45",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Sulawesi Tengah",
        nm_kabupaten: "Kab. Banggai",
        tipe: null,
        id_enc: "VjhoX0tWZXRYQ0E",
        short_narasi:
          "<b>Narasi:</b><br>Desa Transmigrasi tahun 1980-an. Masalah agraria yang terjadi adalah konflik antara masyarakat dengan PT Berkat Hutan Pusaka (BHP) sebagai pihak yang melaksanakan program Hutan Tanaman Industri (HTI) dengan alas hukum Keputusan Ment...",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [119.96057510376, 0.20118672035833],
      },
      properties: {
        idx: "155",
        nomor_kejadian: "108",
        tgl_kejadian: "2017-05-09",
        tahun: "2017",
        judul:
          "Konsesi PT Taman Hutan Asri membuat usulan Masyarakat untuk mendorong Hutan Desa ditolak.",
        clip: "",
        narasi:
          "Tanah-tanah untuk perkebunan warga Panii kini bertumpang tindih dengan kawasan hutan, karena sejak tahun 2012 telah ada peletakan batas kawasan hutan oleh pemerintah (tata batas kawasan). Luas wilayah adminsitratif Panii lebih dari 7.000 Ha, di mana sekitar 2.000 Ha rencananya (tahun 2016)  diajukan untuk skema Hutan Desa (HD). Namun KLHK menolak usulan ini karena ada izin konsesi (IUPHHK-HA) PT Taman Hutan Asri  yang tumpang tindih dengan usulan HD.  AKhirnya, Pemdes dan warga (Maret 2017) menyepakati untuk mendorong Skema TORA di Kawasan Hutan untuk penyelamatan kebun warga.\n",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "Perum Perhutani",
        status_konflik: "BD",
        status_konflik_proses: null,
        tgl_proses: null,
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "2.11",
        investasi: "0",
        dampak: "0",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "72",
        kd_kabupaten: "7208",
        kd_kecamatan: "",
        kd_desa: "",
        longitude: "119.96057510376",
        latitude: "0.20118672035833",
        sumber: "YMP",
        created: "2017-05-09 11:14:44",
        creator: "adminsulteng",
        edited: "2023-01-09 13:31:27",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Sulawesi Tengah",
        nm_kabupaten: "Kab. Parigi Moutong",
        tipe: null,
        id_enc: "WEpWYXVIb2pTLXc",
        short_narasi:
          "<b>Narasi:</b><br>Tanah-tanah untuk perkebunan warga Panii kini bertumpang tindih dengan kawasan hutan, karena sejak tahun 2012 telah ada peletakan batas kawasan hutan oleh pemerintah (tata batas kawasan). Luas wilayah adminsitratif Panii lebih dari ...",
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [120.87810516357, -2.0546894685554],
      },
      properties: {
        idx: "156",
        nomor_kejadian: "108",
        tgl_kejadian: "2017-05-09",
        tahun: "2017",
        judul: "PT PN 14 (PT SPN) menyerobot lahan warga Desa Lee",
        clip: "",
        narasi:
          "HGU PTPN XIV (No. 26/HGU/BPN/RI/2009) yang ditebitkan tanggal 27 Januari 2009 memiliki areal konsesi 15.584 Ha.  Dari luasan konsesi tersebut sekitar 1.895 Ha areal kebun sawit berada pada  tiga desa di Kecamatan Mori Atas yakni Desai Lee, Gontara dan Kasingoli.  Konflik antara PT SPN (Sinergi Perkebunan Nusantara) \u2013 nama baru dari PTPN XIV \u2013 dengan orang Lee mulai timbul ke permukaan sejak tahun 2014, di mana ketika pihak PT SPN rencana melakukan penggusuran lahan dengan mobilisasi alat berat yang dikawal oleh aparat TNI dan Brimob di Desa Lee mendapat perlawanan masyarakat dan pemerintah desa.  Karena mendapat perlawanan masyarakat yang didukung pemerintah desa, maka Pemkab Morowali Utara telah memfasilitasi pertemuan multipihak tanggal 30 Juli 2015 yang mana salah satu rekomendasinya adalah penghentian seluruh operasional kegiatan PT SPN pada lahan klaim masyarakat di areal konsesi HGU PT SPN.",
        kd_sektor: "S3",
        sektor_lain: "",
        kd_konflik: "PTPN",
        status_konflik: "BD",
        status_konflik_proses: null,
        tgl_proses: null,
        tgl_selesai: null,
        jns_pulau: null,
        pulau_umum: null,
        luas: "1.16",
        investasi: "0",
        dampak: "151",
        sifat: "Public",
        kategori: "K2",
        kd_propinsi: "72",
        kd_kabupaten: "7212",
        kd_kecamatan: "",
        kd_desa: "",
        longitude: "120.87810516357",
        latitude: "-2.0546894685554",
        sumber: "YTM & KPA",
        created: "2017-05-09 11:28:24",
        creator: "adminsulteng",
        edited: "2023-01-09 13:31:10",
        editor: "adminazis",
        nama_sektor: "Perkebunan",
        warna_sektor: "#00ff00",
        nm_propinsi: "Sulawesi Tengah",
        nm_kabupaten: "Kab. Morowali Utara",
        tipe: null,
        id_enc: "b2hGVkVEZHllWE0",
        short_narasi:
          "<b>Narasi:</b><br>HGU PTPN XIV (No. 26/HGU/BPN/RI/2009) yang ditebitkan tanggal 27 Januari 2009 memiliki areal konsesi 15.584 Ha.  Dari luasan konsesi tersebut sekitar 1.895 Ha areal kebun sawit berada pada  tiga desa di Kecamatan Mori Atas yakni Des...",
      },
    },
  ],
};
